version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: "postgres-v14"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./tmp/db1:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=superman
      - POSTGRES_USER=superman
      - POSTGRES_DB=superman
